development:
  adapter: postgresql
  encoding: unicode
  database: meal-ordering-dev
  pool: 5
  username: grain
  host: localhost
  port: 5432
  password: grain

test:
  adapter: postgresql
  encoding: unicode
  database: meal-ordering-test
  pool: 5
  username: grain
  host: localhost
  port: 5432
  password: grain

production:
  adapter: postgresql
  encoding: unicode
  url: <%= ENV['DATABASE_URL'] %>
